name: interview_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^9.1.6
  firebase_core: ^1.24.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.11.1
  google_sign_in: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/


